import type { Metadata } from "next";
import Header from "./_components/header";
import Sidebar from "./_components/sidebar";
import { cn } from "@/lib/utils";
import BreakPointIndicator from "./_components/break-point-indicator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className={cn(
            "grid grid-cols-[auto_1fr_1fr]  grid-rows-[auto_1fr_1fr] h-screen bg-background "
          )}
        >
          {/* development only! */}
          <BreakPointIndicator />
          <Header className="col-start-2 col-end-4 row-span-1  border-l" />
          <Sidebar className="col-start-1 col-end-2 row-span-full  border-b h-full  " />
          <div className="col-start-2 col-end-4 row-start-2 row-end-4 p-4 sm:overflow-x-scroll">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
