import type { Metadata } from "next";
import Header from "./_components/header";
import Sidebar from "./_components/sidebar";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={cn("h-screen bg-background root-grid-container")}>
          <Header className="border-l root-grid-container_header " />
          <Sidebar className=" border-b h-full  root-grid-container_sidebar " />
          <div className="p-4 root-grid-container_main">{children}</div>
        </div>
      </body>
    </html>
  );
}
